In [6]:
from flash_attn import flash_attn_qkvpacked_func, flash_attn_func
import torch

In [8]:
flash_attn_qkvpacked_func(torch.tensor([[[[1,1,1]]]]))

IndexError: index 1 is out of bounds for dimension 2 with size 1

In [3]:
import torch

In [16]:
edges = torch.Tensor([[0,1,2,3,1,2], [0,0,0,0,1,2]])

In [17]:
X = torch.zeros(4,4)
for i in range(4):
    X[i, : ] = torch.squeeze(torch.ones(1, 4)*i)
X

tensor([[0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [22]:
X[edges[0].type(torch.long), :], X[edges[1].type(torch.long), :]

(tensor([[0., 0., 0., 0.],
         [1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [1., 1., 1., 1.],
         [2., 2., 2., 2.]]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [1., 1., 1., 1.],
         [2., 2., 2., 2.]]))

In [32]:
X[edges[0].type(torch.long), :].type(torch.long)[edges[1].type(torch.long) == 0].sum(dim=0)

tensor([6, 6, 6, 6])

In [45]:
torch.arange(X.shape[0]).unsqueeze(dim=0)

tensor([[0, 1, 2, 3]])

In [49]:
(edges[1].type(torch.long).repeat(X.shape[0],1).t() == torch.arange(X.shape[0]).unsqueeze(dim=0)).t()

tensor([[ True,  True,  True,  True, False, False],
        [False, False, False, False,  True, False],
        [False, False, False, False, False,  True],
        [False, False, False, False, False, False]])